name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  FIX_RANDOM_SEED: ON

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tbb: [false, true]
        nyanten: [OFF, ON]

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install TBB
        if: matrix.tbb
        run: sudo apt-get update && sudo apt-get install -y libtbb-dev

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DENABLE_NYANTEN=${{matrix.nyanten}} -DFIX_RANDOM_SEED=${{env.FIX_RANDOM_SEED}}

      - name: Build
        if: ${{ !(matrix.tbb && matrix.nyanten == 'ON') }}
        run: cmake --build build --target exclude_index_files

      - name: Build and Pre-calculation
        if: matrix.tbb && matrix.nyanten == 'ON'
        run: cmake --build build

      - name: Run example program
        if: matrix.tbb && matrix.nyanten == 'ON'
        # Run the example program with fixed test parameters (see example program docs for argument semantics)
        run: ./build/example 14 1000000 0

      - name: Upload tables
        uses: actions/upload-artifact@v7
        if: matrix.tbb && matrix.nyanten == 'ON'
        with:
          name: pre-calculated-distance-tables
          path: build/index_*.bin
